// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppName():Promise<string>;

export function ExchangeGoogleToken(arg1:string,arg2:string):Promise<string>;

export function StartGoogleOAuth():Promise<void>;
