// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppName() {
  return window['go']['main']['App']['AppName']();
}

export function ExchangeGoogleToken(arg1, arg2) {
  return window['go']['main']['App']['ExchangeGoogleToken'](arg1, arg2);
}

export function StartGoogleOAuth() {
  return window['go']['main']['App']['StartGoogleOAuth']();
}
