// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppName() {
  return window['go']['main']['App']['AppName']();
}

export function StartGoogleOAuth(arg1) {
  return window['go']['main']['App']['StartGoogleOAuth'](arg1);
}
